/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-10-28 05:24:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class stock_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1661494379773L));
    _jspx_dependants.put("jar:file:/C:/Dowellcommunity/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DowellCommunity/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Dowellcommunity/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DowellCommunity/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>매장재고조회</title>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.12.4.min.js\" ></script>\r\n");
      out.write("<!-- 재고팝업창 자바스크립트 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"./resources/js/stockScript.js\" ></script>\r\n");
      out.write("<!-- 페이지 스타일css -->\r\n");
      out.write("<link href=\"resources/CSS/stock.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"custHidden\"></div>\r\n");
      out.write("	<div id=\"\" class=\"white_content\">\r\n");
      out.write("	<input type=\"hidden\" id=\"trSize\"><!-- tr사이즈 -->\r\n");
      out.write("	<input type=\"hidden\" id=\"checkShop\"><!-- 부모창 검색어 -->\r\n");
      out.write("	<input type=\"hidden\" id=\"saleNum\">\r\n");
      out.write("	<input type=\"hidden\" id=\"num\"><!-- 부모창 버튼값 -->\r\n");
      out.write("		<h3 style=\"text-align: center;\">매장재고조회</h3>\r\n");
      out.write("		<div class=\"CustCheck_Wrap\">\r\n");
      out.write("			<span>매장</span>\r\n");
      out.write("			<input class=\"CustCheck_Info\" id=\"saleName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.prtNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled style=\"margin-right: 26px;\">\r\n");
      out.write("			<span>상품(코드+명)</span>\r\n");
      out.write("			<input class=\"CustCheck_Info\" id=\"goodsCodeName\">\r\n");
      out.write("			<button id=\"Search_but\" onclick=\"checkCust();\">\r\n");
      out.write("				<img class=\"total_search\" src=\"resources/cust_in/search.png\">\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 매장재고조회 내용 -->\r\n");
      out.write("		<table class=\"Cust_stock\" id=\"custTb\">\r\n");
      out.write("			<thead>\r\n");
      out.write("		    	<tr>\r\n");
      out.write("		    		<th class=\"Check_Box\">선택</th>\r\n");
      out.write("		        	<th class=\"goodsNum\">상품코드</th>\r\n");
      out.write("		            <th class=\"goodsName\">상품명</th>\r\n");
      out.write("		            <th class=\"stockCount\">재고수량</th>\r\n");
      out.write("		            <th class=\"custPrice\">소비자가</th>\r\n");
      out.write("		        </tr>\r\n");
      out.write("		    </thead>\r\n");
      out.write("			<tbody id=\"custPopup\">\r\n");
      out.write("			</tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("		<div style=\"text-align: center;margin-top: 36px;\">\r\n");
      out.write("			<button class=\"popupBut\" onclick=\"window.close();\">\r\n");
      out.write("			닫기\r\n");
      out.write("			</button>\r\n");
      out.write("			<button class=\"popupBut\" onclick=\"stock()\">\r\n");
      out.write("			적용\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
